-- MySQL Script generated by MySQL Workbench
-- Wed May 22 19:40:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema actividad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema actividad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `actividad` DEFAULT CHARACTER SET utf8 ;
USE `actividad` ;

-- -----------------------------------------------------
-- Table `actividad`.`Infractor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Infractor` (
  `documento` INT NOT NULL,
  `tipo_doc` VARCHAR(45) NULL,
  `nombre_inf` VARCHAR(45) NULL,
  `apellido_inf` VARCHAR(45) NULL,
  PRIMARY KEY (`documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`Agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Agente` (
  `id_agente` INT NOT NULL,
  `nombre_age` VARCHAR(45) NULL,
  `apellido_age` VARCHAR(45) NULL,
  `rango_age` VARCHAR(45) NULL,
  PRIMARY KEY (`id_agente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`comparendo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`comparendo` (
  `ID_comparendo` INT NOT NULL,
  `Valor_com` FLOAT NULL,
  PRIMARY KEY (`ID_comparendo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`Infraccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Infraccion` (
  `Id_infraccion` INT NOT NULL,
  `Tipo_inf` VARCHAR(45) NULL,
  `descripcion_inf` TEXT(800) NULL,
  `Fecha_inf` DATE NULL,
  `Hora_inf` TIME NULL,
  `comparendo_ID_comparendo` INT NOT NULL,
  PRIMARY KEY (`Id_infraccion`, `comparendo_ID_comparendo`),
  INDEX `fk_Infraccion_comparendo1_idx` (`comparendo_ID_comparendo` ASC) ,
  CONSTRAINT `fk_Infraccion_comparendo1`
    FOREIGN KEY (`comparendo_ID_comparendo`)
    REFERENCES `actividad`.`comparendo` (`ID_comparendo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Veiculo` (
  `Placa_vei` VARCHAR(6) NOT NULL,
  `Clase_vei` VARCHAR(45) NULL,
  `Nombre_pro` VARCHAR(45) NULL,
  PRIMARY KEY (`Placa_vei`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`Infractor_has_Infraccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Infractor_has_Infraccion` (
  `Infractor_Documento` INT NOT NULL,
  `Infraccion_Id_infraccion` INT NOT NULL,
  PRIMARY KEY (`Infractor_Documento`, `Infraccion_Id_infraccion`),
  INDEX `fk_Infractor_has_Infraccion_Infraccion1_idx` (`Infraccion_Id_infraccion` ASC) ,
  INDEX `fk_Infractor_has_Infraccion_Infractor_idx` (`Infractor_Documento` ASC) ,
  CONSTRAINT `fk_Infractor_has_Infraccion_Infractor`
    FOREIGN KEY (`Infractor_Documento`)
    REFERENCES `actividad`.`Infractor` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Infractor_has_Infraccion_Infraccion1`
    FOREIGN KEY (`Infraccion_Id_infraccion`)
    REFERENCES `actividad`.`Infraccion` (`Id_infraccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`Agente_has_Infraccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Agente_has_Infraccion` (
  `Agente_ID_agente` INT NOT NULL,
  `Infraccion_Id_infraccion` INT NOT NULL,
  PRIMARY KEY (`Agente_ID_agente`, `Infraccion_Id_infraccion`),
  INDEX `fk_Agente_has_Infraccion_Infraccion1_idx` (`Infraccion_Id_infraccion` ASC) ,
  INDEX `fk_Agente_has_Infraccion_Agente1_idx` (`Agente_ID_agente` ASC) ,
  CONSTRAINT `fk_Agente_has_Infraccion_Agente1`
    FOREIGN KEY (`Agente_ID_agente`)
    REFERENCES `actividad`.`Agente` (`id_agente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agente_has_Infraccion_Infraccion1`
    FOREIGN KEY (`Infraccion_Id_infraccion`)
    REFERENCES `actividad`.`Infraccion` (`Id_infraccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`Veiculo_has_Infraccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Veiculo_has_Infraccion` (
  `Veiculo_Placa_vei` INT NOT NULL,
  `Infraccion_Id_infraccion` INT NOT NULL,
  PRIMARY KEY (`Veiculo_Placa_vei`, `Infraccion_Id_infraccion`),
  INDEX `fk_Veiculo_has_Infraccion_Infraccion1_idx` (`Infraccion_Id_infraccion` ASC) ,
  INDEX `fk_Veiculo_has_Infraccion_Veiculo1_idx` (`Veiculo_Placa_vei` ASC) ,
  CONSTRAINT `fk_Veiculo_has_Infraccion_Veiculo1`
    FOREIGN KEY (`Veiculo_Placa_vei`)
    REFERENCES `actividad`.`Veiculo` (`Placa_vei`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_has_Infraccion_Infraccion1`
    FOREIGN KEY (`Infraccion_Id_infraccion`)
    REFERENCES `actividad`.`Infraccion` (`Id_infraccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`Infractor_has_Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Infractor_has_Veiculo` (
  `Infractor_Documento` INT NOT NULL,
  `Veiculo_Placa_vei` INT NOT NULL,
  PRIMARY KEY (`Infractor_Documento`, `Veiculo_Placa_vei`),
  INDEX `fk_Infractor_has_Veiculo_Veiculo1_idx` (`Veiculo_Placa_vei` ASC) ,
  INDEX `fk_Infractor_has_Veiculo_Infractor1_idx` (`Infractor_Documento` ASC) ,
  CONSTRAINT `fk_Infractor_has_Veiculo_Infractor1`
    FOREIGN KEY (`Infractor_Documento`)
    REFERENCES `actividad`.`Infractor` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Infractor_has_Veiculo_Veiculo1`
    FOREIGN KEY (`Veiculo_Placa_vei`)
    REFERENCES `actividad`.`Veiculo` (`Placa_vei`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`.`Infraccion_has_comparendo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad`.`Infraccion_has_comparendo` (
  `Infraccion_Id_infraccion` INT NOT NULL,
  `comparendo_ID_comparendo` INT NOT NULL,
  PRIMARY KEY (`Infraccion_Id_infraccion`, `comparendo_ID_comparendo`),
  INDEX `fk_Infraccion_has_comparendo_comparendo1_idx` (`comparendo_ID_comparendo` ASC) ,
  INDEX `fk_Infraccion_has_comparendo_Infraccion1_idx` (`Infraccion_Id_infraccion` ASC) ,
  CONSTRAINT `fk_Infraccion_has_comparendo_Infraccion1`
    FOREIGN KEY (`Infraccion_Id_infraccion`)
    REFERENCES `actividad`.`Infraccion` (`Id_infraccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Infraccion_has_comparendo_comparendo1`
    FOREIGN KEY (`comparendo_ID_comparendo`)
    REFERENCES `actividad`.`comparendo` (`ID_comparendo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
